### PR TITLE
microsoft.data.sqlclient

### PR DESCRIPTION
**Pull request by ladislavd3s**
Replace System.Data.SqlClient with Microsoft.Data.SqlClient

### CODE REVIEW

**Comment by peetw** [comment]
@ladislavd3s do you mind rebasing onto the latest version of master? It looks like the build failed due to MS changing one of their download URLs, which I have now fixed on master, so rebasing will kick off a fresh build that hopefully succeeds.

**Comment by wilbit** [comment]
Hello, there.
I very need NHibernate.Spatial.MsSql with Microsoft.Data.SqlClient dependency in our project, instead of System.Data.SqlClient.
What are the next steps for this PR?
@ladislavd3s , will you do what @peetw asked for?
Otherwise, I suppose, somebody has to cancel this PR,  and I can create another one.

**Comment by peetw** [comment]
@wilbit Fixed in NHibernate.Spatial.MsSql 6.1.0

**Comment by wilbit** [comment]
That's awesome. Thanks, @peetw !

**Pull request closed without merging**
