### PR TITLE
Set up AppVeyor continuous integration

### PR DESCRIPTION
**Pull request by peetw**
Builds the solution and runs the tests whenever a commit is pushed.

Uses the database versions listed in #80 when running the tests. The only tests still failing are a lot of the MySQL ones (really confused as to which version of MySQL it's meant to be targeting so I can't really fix the tests) and a few of the MySQL57 ones (mostly related to a bug in the MySql ADO.NET MySqlGeometry type - see my bug report [here](https://bugs.mysql.com/bug.php?id=86974))

### CODE REVIEW

**Comment by peetw** [comment]
@andrerav I believe you'll need to create an "nhibernate" account on AppVeyor as I don't have admin privileges for this project...

**Comment by fredericDelaporte** [comment]
I have added the AppVeyor build account. Unfortunately it is failing.

**Comment by peetw** [comment]
@fredericDelaporte great, thanks! I assume it's the MySQL tests that are failing, and not the build itself? Do you have a link to the AppVeyor project?

**Comment by fredericDelaporte** [comment]
I have build master, so you have the failing status on the front page... Maybe not a good idea to launch that branch build, but now it is done.

https://ci.appveyor.com/project/nhibernate/nhibernate-spatial

**Comment by peetw** [comment]
Hmm, looks like the PostGIS installer has moved! I'll update the AppVeyor script

**Comment by peetw** [comment]
Ok, I've got the config fixed for the PostGIS issue (see [this commit](https://github.com/peetw/NHibernate.Spatial/commit/ba067c37a5c4be3cf6fcb058986fdd51f9ffb179)), but it looks like it's now failing some of the MsSQL and PostGIS tests, which it shouldn't be. I suspect that AppVeyor have updated some of the config on their end.

I'm heading out now, but I'll look into it later :)

**Comment by peetw** [comment]
Phew, that was a long and frustrating process, but I finally worked out what was causing the MsSQL/PostGIS tests to fail - AppVeyor was discovering the tests by scan the build folder recursively, which was picking up the test assemblies multiple times (since the PostGIS20 tests reference the PostGIS tests and likewise for the MsSQL tests).

However, as stated in the [original post](https://github.com/nhibernate/NHibernate.Spatial/pull/83#issue-240974238), the MySQL tests are still failing. This means that the build status badge on the NHibernate.Spatial front page still displays "failing". @fredericDelaporte @andrerav @suryapratap - given that I'm not sure how to resolve these tests, should I just disable them from the AppVeyor testing for now?

**Comment by fredericDelaporte** [comment]
Yes I think it is better to disable the failing test till we know how to fix them.

**Pull request merged**
